spring:
  datasource:
    url: jdbc:h2:mem:produtos
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: always